---
title: "Stat 547"
author: "Yining Zhou"
date: "2023-11-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(cluster)
library(mvtnorm)
library(MASS)
library(GGally)
library(klaR)
library(dendextend)
library(gridExtra)
set.seed(1)
```

##  data load and clean
```{r data load and clean}
HDP <- read.csv("heart_disease_patients.csv")
colSums(is.na(HDP))
```

## declare cp

```{r}
HDP$sex <- ifelse(HDP$sex == 1 , "Male", ifelse(HDP$sex == 0, "Female", HDP$sex))
HDP$sex[1]
class(HDP$sex)
```

```{r}
ggplot(HDP,aes(x = sex, fill = sex)) + 
  geom_bar()

ggplot(HDP,aes(x=age))+
  geom_histogram(binwidth = 5, fill="blue",color = "black", alpha = 0.5) + 
  labs(x = "Age")


ggplot(HDP, aes(x = sex, fill = factor(age))) +
  geom_bar(position = "dodge") + 
  labs(title = "Distribution of Age by Gender",
       x = "Gender",
       y = "Count",
       fill = "Age")+
  scale_color_viridis_d()
```


## Declare the meaning of "cp"

```{r}
p1 <- ggplot(HDP, aes(x = sex, fill = factor(cp))) +
  geom_bar(position = "dodge")

p2 <- ggplot(HDP, aes(x = age, fill = factor(cp))) +
  geom_bar(position = "dodge")


## Serious ranking 4<3<2<1
grid.arrange(p1, p2, ncol = 2)
```

```{R}
HDP_cat <- HDP[, names(HDP) %in% c('id','sex','cp', 'fbs','restecg','exang','slope')]
```



## overview

```{r}
HDP_num <- HDP[, !names(HDP) %in% c('id','sex','cp', 'fbs','restecg','exang','slope')]

plotPerColumnDistribution <- function(df) {
  par(mfrow=c(3, 2),oma=c(0, 1, 1, 0), mar=c(2, 2, 2, 0))
  
  for (col in colnames(df)) {
    hist(df[[col]], main=col, xlab=col, col="lightblue", border="black")
    
  }
  
  par(mfrow=c(1, 1))  # Resetting the plotting layout
}

plotPerColumnDistribution(HDP_num)
length(HDP$id)

```


```{r}

numerical_vars <- colnames(HDP_num)


ggpairs(HDP, columns = numerical_vars, aes(color = sex), 
        title = "Pair Plot of Numerical Variables by Sex",
        upper = list(continuous = "points", combo = "points")) +
  theme(legend.position = "top")  

```



## Hierarchical Cluster

```{R}
HDP_num_stand1 <- scale(HDP_num)
eucdist <- dist(HDP_num_stand1,method="euclidean")
clus3 <- hclust(eucdist, method="complete")
avg_dend_obj <- as.dendrogram(clus3)
avg_col_dend <- color_branches(avg_dend_obj, h = 6)
plot(avg_col_dend,main = "Hierarchical Cluster (Standardized)", sub = "", xlab = "Observations", ylab = "Distance", cex = 0.8)
  
  HDP_num_stand2 <- apply(HDP_num, 2, function(x) (x - min(x)) / (max(x) - min(x)))
eucdist <- dist(HDP_num_stand2,method="euclidean")
clus3 <- hclust(eucdist, method="complete")
avg_dend_obj <- as.dendrogram(clus3)
avg_col_dend <- color_branches(avg_dend_obj, h = 0.93)
  plot(avg_col_dend,main = "Hierarchical Cluster(Normalized)", sub = "", xlab = "Observations", ylab = "Distance", cex = 0.8)
  
```




## k-menas
```{r k-menas}
set.seed(1)

clust_red <- kmeans(HDP_num_stand2, centers = 4)

classification = clust_red$cluster

length(clust_red$cluster)

par(mfrow=c(1, 4),oma=c(2, 1, 1, 0))

plot(HDP$age, HDP$trestbps, pch = as.numeric(classification),col = as.numeric(classification) + 2, xlab = "Age", ylab = "trestbps")

plot(HDP$age, HDP$chol, pch = as.numeric(classification),col = as.numeric(classification) + 2, xlab = "Age", ylab = "chol")

plot(HDP$age, HDP$oldpeak, pch = as.numeric(classification),col = as.numeric(classification) + 2, xlab = "Age", ylab = "oldpeak")

plot(HDP$age, HDP$thalach, pch = as.numeric(classification),col = as.numeric(classification) + 2, xlab = "Age", ylab = "thalach")


```


```{r}
par(mfrow=c(1,3))

plot(HDP$trestbps, HDP$chol, pch = as.numeric(classification),col = as.numeric(classification) + 2, xlab = "trestbps", ylab = "chol")

plot(HDP$trestbps, HDP$thalach, pch = as.numeric(classification),col = as.numeric(classification) + 2, xlab = "trestbps", ylab = "thalach")

plot(HDP$trestbps, HDP$oldpeak, pch = as.numeric(classification),col = as.numeric(classification) + 2, xlab = "trestbps", ylab = "oldpeak")
```

```{r}
par(mfrow=c(1,3))

plot(HDP$chol, HDP$thalach,pch = as.numeric(classification),col = as.numeric(classification) + 2, xlab = "chol", ylab = "thalach")

plot(HDP$chol, HDP$oldpeak,pch = as.numeric(classification),col = as.numeric(classification) + 2, xlab = "chol", ylab = "oldpeak")

plot(HDP$thalach, HDP$oldpeak, pch = as.numeric(classification),col = as.numeric(classification) + 2, xlab = "thalach", ylab = "oldpeak")
```




```{r}

set.seed(1)

thalach_oldpeak <- data.frame(cbind(HDP_num$thalach, HDP_num$oldpeak, classification))

colnames(thalach_oldpeak) <- c("thalach", "oldpeak","classification")

plot(thalach_oldpeak$thalach, thalach_oldpeak$oldpeak, pch=classification, col=classification+2,xlab = "Resting blood pressure", ylab = "ST depression")


par(mfrow = c(2,2))

rda_data <- data.frame(cbind(HDP_num$thalach,HDP_num$oldpeak))
colnames(rda_data) <- c("thalach", "oldpeak")

## LDA
alpha0gamma0 <- rda(rda_data, grouping = classification, regularization = c(0, 1))
p00 <- predict(alpha0gamma0)
plot(rda_data, pch = as.numeric(p00$class), col = as.numeric(p00$class) + 2, main = "LDA", xlab = "Resting blood pressure", ylab = "ST depression")

## QDA
alpha1gamma0 <- rda(rda_data, grouping = classification, regularization = c(0, 0))
p10 <- predict(alpha1gamma0)
plot(rda_data, pch = as.numeric(p10$class), col = as.numeric(p10$class) + 2, main = "QDA", xlab = "Resting blood pressure", ylab = "ST depression")

## Special
alpha1gamma1 <- rda(rda_data, grouping = classification, regularization = c(1, 0))
p11 <- predict(alpha1gamma1)
plot(rda_data, pch = as.numeric(p11$class), col = as.numeric(p11$class) + 2, main = "Group-specific Scalar Variance", xlab = "Resting blood pressure", ylab = "ST depression")

## Scalar
alpha0gamma1 <- rda(rda_data, grouping = classification, regularization = c(1, 1))
p01 <- predict(alpha0gamma1)
plot(rda_data, pch = as.numeric(p01$class), col = as.numeric(p01$class) + 2, main = "Scalar Variance", xlab = "Resting blood pressure", ylab = "ST depression")



```



```{R}

classification2 <- as.numeric(p00$class)

HDP_num$clust <- classification2

lda <- lda(clust~., data = HDP_num, CV = TRUE)


table(HDP_num$clust,lda$class)


qda <- qda(clust~., data = HDP_num, CV = TRUE)

table(HDP_num$clust,qda$class)

```


```{r}
set.seed(1)

clust_red <- kmeans(HDP_num_stand2, centers = 4)

classification = clust_red$cluster

HDP_num$clust <- classification

### Cluster 1
H1 <- HDP_num[HDP_num$clust == 1, ]
means_H1 <- colMeans(H1, na.rm = TRUE)
print(round(means_H1,3))

### Cluster 2
H2 <- HDP_num[HDP_num$clust == 2, ]
means_H2 <- colMeans(H2, na.rm = TRUE)
print(round(means_H2,3))


### Cluster 
H3 <- HDP_num[HDP_num$clust == 3, ]
means_H3 <- colMeans(H3, na.rm = TRUE)
print(round(means_H3,3))


### Cluster 
H4 <- HDP_num[HDP_num$clust == 4, ]
means_H4 <- colMeans(H4, na.rm = TRUE)
print(round(means_H4,3))
```



